project_id = "ciasptvokbttjuldenxc"

[functions.admin-create-user]
verify_jwt = false

[functions.admin-create-student]
verify_jwt = false

[functions.admin-delete-user]
verify_jwt = false

[functions.admin-update-email]
verify_jwt = false

[functions.admin-update-password]
verify_jwt = false

[functions.create-test-user]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.send-email-resend]
verify_jwt = false

[functions.generate-abet-course]
verify_jwt = false

[functions.generate-curriculum-v2]
verify_jwt = false

[functions.generate-course-content]
verify_jwt = false

[functions.process-content-queue]
verify_jwt = false