project_id = "ciasptvokbttjuldenxc"

[functions.create-test-user]
verify_jwt = false

[functions.generate-invoice]
verify_jwt = false

[functions.send-email-resend]
verify_jwt = false

[functions.generate-abet-course]
verify_jwt = false